version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI